# Generated by Django 2.2.5 on 2020-01-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
