# Generated by Django 2.2.5 on 2020-01-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200113_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='id_autor',
        ),
        migrations.AddField(
            model_name='examen',
            name='nombre_usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
