# Generated by Django 2.2.5 on 2020-01-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': ('Autor',),
                'verbose_name_plural': ('Autores',),
                'db_table': 'autor',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nonbre', models.CharField(max_length=100)),
                ('Autor', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='autor_del_examen', to='quiz.Autor')),
            ],
            options={
                'verbose_name': ('Examen',),
                'verbose_name_plural': ('Examenes',),
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=200)),
                ('opcion1', models.CharField(max_length=50)),
                ('opcion2', models.CharField(max_length=50)),
                ('opcion3', models.CharField(max_length=50)),
                ('opcion4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_del_examen', to='quiz.Examen')),
            ],
            options={
                'verbose_name': ('Pregunta',),
                'verbose_name_plural': ('Preguntas',),
                'db_table': 'preguntas',
            },
        ),
    ]
