# Generated by Django 2.2.5 on 2020-01-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='Autor',
            new_name='id_autor',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='nonbre',
            new_name='nombre',
        ),
    ]
