# Generated by Django 2.2.5 on 2020-01-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200114_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion3',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion4',
        ),
    ]
